name: Update Locations

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3 cabextract
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update script
        run: python update.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add locations.json products/
          if ! git diff --cached --quiet; then
            git commit -m "Update locations.json"
            git push
          else
            echo "No changes to commit"
          fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}